#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-mysql-update event
#--------------------------------------------------

my $event = "nethserver-mysql-update";

event_actions($event,
              'initialize-default-databases' => '00',
              'nethserver-mysql-conf' => '02',
              'firewall-adjust' => '30',
              'runlevel-adjust' => '40');
templates2events("/etc/my.cnf",  $event);
templates2events("/root/.my.cnf",  $event);
event_services($event, 'mysqld' => 'restart');


#--------------------------------------------------
# actions for nethserver-mysql-save event
#--------------------------------------------------

$event = "nethserver-mysql-save";

templates2events("/etc/my.cnf",  $event);
templates2events("/root/.my.cnf",  $event);
event_services($event, 'mysqld' => 'restart');


#--------------------------------------------------
# actions for nethserver-mysql-uninstall event
#--------------------------------------------------

$event = "nethserver-mysql-uninstall";

event_actions($event,
              'nethserver-mysqld-uninstall' => '02',
              'firewall-adjust' => '40',
              'runlevel-adjust' => '50');


exit;

