#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-mysql-update event
#--------------------------------------------------

my $event = "nethserver-mysql-update";

event_actions($event,
              'initialize-default-databases' => '00',
              'nethserver-mysql-conf' => '02',
              'firewall-adjust' => '30',
              'runlevel-adjust' => '40');
templates2events("/etc/my.cnf",  $event);
templates2events("/root/.my.cnf",  $event);
event_services($event, 'mysqld' => 'restart');


#--------------------------------------------------
# actions for nethserver-mysql-save event
#--------------------------------------------------

$event = "nethserver-mysql-save";

templates2events("/etc/my.cnf",  $event);
templates2events("/root/.my.cnf",  $event);
event_services($event, 'mysqld' => 'restart');


#--------------------------------------------------
# actions for nethserver-mysql-uninstall event
#--------------------------------------------------

$event = "nethserver-mysql-uninstall";

event_actions($event,
              'nethserver-mysql-uninstall' => '02',
              'firewall-adjust' => '40',
              'runlevel-adjust' => '50');


#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-mysql-migrate' => 50);


#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = "pre-backup-data";
event_actions($event, 'mysql-dump-tables' => 50);


#--------------------------------------------------
# actions for post-backup-data event
#--------------------------------------------------

$event = "post-backup-data";
event_actions($event, 'mysql-delete-dumped-tables' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = "post-restore-data";
event_actions($event, 
                     'mysql-load-tables' => 50,
                     'mysql-delete-dumped-tables' => 60);


exit;
