#!/bin/sh
#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# This script will restore mariadb backup.
# The script mut be executed before /etc/.my.cnf is replaced by an expand-template

backup_dir=/var/lib/nethserver/backup/mysql/

if [ ! -f $backup_dir/mysql.dump ]; then
    exit 0
fi

echo "Restoring mariadb backup...";
/usr/bin/systemctl status mysqld  >/dev/null
if [ $? -eq 0 ]; then
    /usr/bin/systemctl stop mysqld >/dev/null
fi

# Restarting mysql without privileges
/usr/bin/mysqld_safe --skip-grant-tables&
/usr/bin/mysql -e 'show databases'&> /dev/null
while [ $? -ne 0 ]  # wait mysql to start
do
    sleep 1
    /usr/bin/mysql -e 'show databases'&> /dev/null
done


# drop mysql db if exists (backup restored after nethserver-mysql install)
/usr/bin/mysql -e "drop database mysql" 2>/dev/null
/usr/bin/mysql < $backup_dir/mysql.dump
if [ $? -ne 0 ]; then
    echo "Can't load mysql.dump backup"
    exit 1
fi

rm -f $backup_dir/mysql.dump

newpass=$(cat /var/lib/nethserver/secrets/mysql)
/usr/bin/mysql mysql -u root -e "update user set password=PASSWORD(\"$newpass\") where User='root'; flush privileges;"

# Stop all mysql instances
/usr/bin/killall mysqld
sleep 1

# restart mysqld as normal daemon
/usr/bin/systemctl restart mysqld

# update .my.cnf with new password
/sbin/e-smith/expand-template /root/.my.cnf

# restore all dumps
for db in $(ls $backup_dir/*.dump 2> /dev/null)
do
    mv $db /etc/e-smith/sql/init/01_$(basename $db .dump).sql
done

exec /etc/e-smith/events/actions/nethserver-mysql-init
