#!/bin/sh

status=$(/sbin/e-smith/config getprop mysqld status)
if [ "$status" = "disabled" ]
then
    echo "mysqld is disabled - no tables restored" >&2
    exit 0
fi
if [ ! -f /var/lib/mysql/mysql/user.frm ]
then
    for db in $(ls /home/e-smith/db/mysql/*.dump 2> /dev/null | grep -v '/mysql.dump')
    do
        mv $db /etc/e-smith/sql/init/01_$(basename $db .dump).sql
    done
fi
