#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

if [[ ! -f /var/lib/mysql/mysql/user.frm ]]; then 
   # mysql is not configured do it now!
   echo "[NOTICE] starting mysql initial configuration"
   exec /etc/e-smith/events/actions/nethserver-mysql-conf
fi

echo "[NOTICE] restoring mysql root password"

# read password from backup-config
newpass=$(cat /var/lib/nethserver/secrets/mysql)
/usr/bin/mysql mysql -u root <<EOF
	update user set password=PASSWORD("$newpass") where User='root'; 
	flush privileges;
EOF

# update .my.cnf with new password
/sbin/e-smith/expand-template /root/.my.cnf


